language: node_js
addons:
  sonarcloud:
    organization: "rafaelnsantos-github"
node_js:
  - "8.1"
install:
  - npm install
script:
  - npm test
  - sonar-scanner -Dsonar.javascript.lcov.reportPath=coverage/lcov.info -Dsonar.language=js -Dsonar.projectKey=test-mocha -Dsonar.tests=test -Dsonar.organization=rafaelnsantos-github -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
