language: node_js
addons:
  sonarcloud:
    organization: "rafaelnsantos-github"
node_js:
  - "8.1"
install:
  - npm install
script:
  - sonar-scanner -Dsonar.projectKey=test-mocha -Dsonar.organization=rafaelnsantos-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
  - npm test
